Add port of coxnet algorihm of R's glmnet package
Implements the coxnet algorithm in C++ using Eigen

Add coxnet example from glmnet package

Add tests for deviance_ratio_ attribute

FIX compute maybe_active_set in second iteration:
Set alpha_old before multiplying by factor, otherwise
all coefficients would be activated

Fix issues with MSVC:
* no support for constexpr
* coxnet\data.h(33) : error C2873: 'Index' : symbol cannot be used in a using-declaration
* no support for deleted and defaulted functions
* Template arguments are not allowed to start with _
* std:map::emplace expects std::pair

Fix code issues

Add CoxnetSurvivalAnalysis to API doc

Closes #12